-- ============================================================
-- 削除ログ（モデレーション用）
--   投稿/教科書投稿/その返信が削除される瞬間に、内容を運営専用ログへ控える。
--   通報の有無に関わらず「削除された全コンテンツ」を一定期間保持し、
--   後日のトラブル（削除された後に被害が判明 等）に備える。
--   実行順：schema.sql の後（対象テーブルが存在していれば、いつ実行してもOK）。冪等。
-- ============================================================

create table if not exists public.deleted_content_log (
  id                  bigint generated by default as identity primary key,
  content_type        text not null,        -- 'post' | 'txt_post' | 'txt_post_reply'
  content_id          bigint not null,
  author_id           uuid,
  content             text,
  image               text,                 -- 画像URL（txt_post は JSON配列文字列のことがある）
  original_created_at timestamptz,
  deleted_at          timestamptz not null default now()
);

alter table public.deleted_content_log enable row level security;

-- 閲覧は運営のみ。insert/update/delete のポリシーは置かない
--（書き込みは下の SECURITY DEFINER トリガー、パージは purge 関数のみ）
drop policy if exists "staff reads deleted log" on public.deleted_content_log;
create policy "staff reads deleted log" on public.deleted_content_log
  for select to authenticated
  using (exists (select 1 from staff_members s where s.user_id = auth.uid()));

-- 削除される行の内容をログへ控える汎用トリガー関数。
-- to_jsonb(OLD) で列名の違い（post.content / txt_post.description / reply.img_url 等）を吸収。
create or replace function public.log_deleted_content()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare j jsonb := to_jsonb(OLD);
begin
  insert into public.deleted_content_log
    (content_type, content_id, author_id, content, image, original_created_at)
  values (
    tg_table_name,
    (j->>'id')::bigint,
    (j->>'user_id')::uuid,
    coalesce(j->>'content', j->>'description'),
    coalesce(j->>'image_url', j->>'image_urls', j->>'img_url'),
    (j->>'created_at')::timestamptz
  );
  return old;
end;
$$;

-- どの削除経路（クライアント直接 / RPC / カスケード）でも確実に残る BEFORE DELETE トリガー
drop trigger if exists trg_log_deleted on public.post;
create trigger trg_log_deleted before delete on public.post
  for each row execute function public.log_deleted_content();

drop trigger if exists trg_log_deleted on public.txt_post;
create trigger trg_log_deleted before delete on public.txt_post
  for each row execute function public.log_deleted_content();

drop trigger if exists trg_log_deleted on public.txt_post_reply;
create trigger trg_log_deleted before delete on public.txt_post_reply
  for each row execute function public.log_deleted_content();

-- 保持期間を過ぎたログを削除する関数（既定90日）。プライバシー配慮で無期限保持しない。
create or replace function public.purge_deleted_content_log(p_days int default 90)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare n integer;
begin
  delete from public.deleted_content_log
   where deleted_at < now() - (p_days || ' days')::interval;
  get diagnostics n = row_count;
  return n;
end;
$$;

revoke execute on function public.purge_deleted_content_log(int) from anon, public;

-- （任意）毎日3:00に90日超のログを自動パージ。pg_cron が必要。
--   下の2行のコメントを外して実行するとスケジュール登録される。
-- create extension if not exists pg_cron;
-- select cron.schedule('purge_deleted_content_log', '0 3 * * *', $$select public.purge_deleted_content_log(90)$$);
