-- ============================================================
-- 本番DB スキーマ（本番で使用する15テーブルのみ）
-- 新しい Supabase プロジェクトの SQL Editor で、上から順に実行してください。
-- 依存関係（親→子）の順に並べています。
--
-- 前提：
--  - public."user".id は Supabase Auth の auth.users.id と同じ uuid。
--    サインアップ時にトリガー（handle_new_user 等）で作成します（別途）。
--  - このファイルの後に:
--      1) txt_request_functions.sql（RPC・トリガー）
--      2) rls_policies.sql（RLSポリシー・いいねトリガー）
--      3) サインアップ用トリガー（auth.users → public.user 作成）
--      4) シードデータ（faculty / department / txtbook_condition / textbook）
--      5) Storage バケット＋ポリシー、公式ユーザー、staff_members
--    を適用します（下部のチェックリスト参照）。
-- ============================================================

-- ---------- 参照マスタ ----------
create table public.faculty (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table public.department (
  id         bigint generated by default as identity primary key,
  faculty_id bigint not null references public.faculty(id),
  name       text not null
);

create table public.txtbook_condition (
  id   bigint generated by default as identity primary key,
  name text not null
);

-- ---------- ユーザー ----------
-- id は auth.users.id と一致（サインアップトリガーで作成）。
-- FK を付けて、Auth ユーザー削除時にプロフィールも消えるようにする（現行より堅牢）。
create table public."user" (
  id                  uuid primary key references auth.users(id) on delete cascade,
  username            text not null,
  grade               bigint,
  department_id       bigint references public.department(id),
  icon_src            text,
  bio                 text,
  points              integer not null default 1000,
  is_official         boolean not null default false,
  total_earned_points bigint  not null default 0,
  reserved_points     integer not null default 0
);

create table public.textbook (
  id         bigint generated by default as identity primary key,
  title      text not null,
  author     text,
  publisher  text,
  isbn       text unique,
  pub_year   text,
  price      bigint,      -- 取引で使うポイント価格
  list_price integer,     -- ユーザー入力の定価（price = round(list_price*0.4)）
  confirmed  boolean not null default false
);

-- ---------- ホーム投稿・いいね ----------
create table public.post (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references public."user"(id),
  content         text not null,
  image_url       text,
  created_at      timestamp not null default now(),
  number_of_likes bigint not null default 0,
  reply_to_id     bigint references public.post(id) on delete cascade,
  parent_id       bigint references public.post(id) on delete cascade
);

create table public."like" (
  id      bigint generated by default as identity primary key,
  user_id uuid   not null references public."user"(id) on delete cascade,
  post_id bigint not null references public.post(id) on delete cascade
);

-- ---------- 教科書譲渡 ----------
create table public.txt_post (
  id           bigint generated by default as identity primary key,
  give_type    text not null,                 -- 'offering' | 'seeking'
  user_id      uuid not null references public."user"(id),
  textbook_id  bigint not null references public.textbook(id),
  condition_id bigint references public.txtbook_condition(id),
  description  text,
  status       text not null,                 -- '募集中' | 'マッチング済み'
  created_at   timestamptz not null default now(),
  image_urls   text,                          -- JSON配列文字列で保存
  points       bigint not null default 500,   -- 取引額（作成時に textbook.price を凍結）
  reserved_points integer                     -- seeking の投稿時予約額（offering は null）
);

create table public.txt_transaction (
  id           bigint generated by default as identity primary key,
  txt_post_id  bigint not null references public.txt_post(id),
  giver_id     uuid not null references public."user"(id),
  receiver_id  uuid not null references public."user"(id),
  status       text not null default 'pending', -- pending/matched/completed/cancelled
  points       bigint,
  completed_at timestamptz not null default now(),
  is_read      boolean not null default false
);

create table public.txt_post_reply (
  id          bigint generated by default as identity primary key,
  txt_post_id bigint not null references public.txt_post(id),
  user_id     uuid not null references public."user"(id),
  content     text not null,
  img_url     text,
  created_at  timestamptz not null default now()
);

-- ---------- DM ----------
create table public.chat (
  id            uuid primary key default gen_random_uuid(),
  sender_id     uuid references public."user"(id),
  receiver_id   uuid not null references public."user"(id),
  content       text,
  created_at    timestamptz default now(),
  reply_to_id   uuid,
  reply_content text
);

-- ---------- 通知 ----------
create table public.notification (
  id                 bigint generated by default as identity primary key,
  receiver_id        uuid not null references public."user"(id),
  sender_id          uuid references public."user"(id),
  notification_type  text,
  txt_post_id        bigint references public.txt_post(id),
  chat_id            uuid references public.chat(id) on delete cascade,
  is_read            boolean not null default false,
  created_at         timestamptz not null default now(),
  request_status     text check (request_status in ('accepted','rejected')),
  txt_transaction_id bigint references public.txt_transaction(id)
);

-- ---------- フォロー ----------
create table public.follows (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  follower_id  uuid references public."user"(id) on update cascade on delete cascade,
  following_id uuid references public."user"(id) on update cascade on delete cascade,
  unique (follower_id, following_id)
);

-- ---------- 通報 ----------
create table public.report (
  id                bigint generated by default as identity primary key,
  reporter_id       uuid not null references public."user"(id),
  reporterd_user_id uuid not null references public."user"(id),
  target_type       text not null,   -- 'txt_post' | 'post' | 'user' | 'message'
  target_id         text not null,
  reason_type       text not null,
  reason_detail     text,
  status            text not null,   -- 'pending' | 'resolved' | 'dismissed'
  snapshot_content  text,            -- 通報時点の内容（本文/説明/ユーザー名）
  snapshot_image    text,            -- 通報時点の画像URL（txt_post は JSON配列文字列）
  created_at        timestamptz not null default now()
);

-- ---------- 運営 ----------
create table public.staff_members (
  id         integer generated by default as identity primary key,
  user_id    uuid not null unique references auth.users(id),
  role       text not null,
  created_at timestamp default now(),
  created_by uuid references auth.users(id)
);


-- ============================================================
-- RLS を全テーブルで有効化（この後 rls_policies.sql でポリシーを作成）
-- ============================================================
alter table public.faculty            enable row level security;
alter table public.department         enable row level security;
alter table public.txtbook_condition  enable row level security;
alter table public."user"             enable row level security;
alter table public.textbook           enable row level security;
alter table public.post               enable row level security;
alter table public."like"             enable row level security;
alter table public.txt_post           enable row level security;
alter table public.txt_transaction    enable row level security;
alter table public.txt_post_reply     enable row level security;
alter table public.chat               enable row level security;
alter table public.notification       enable row level security;
alter table public.follows            enable row level security;
alter table public.report             enable row level security;
alter table public.staff_members      enable row level security;
