drop extension if exists "pg_net";


  create table "public"."appartment" (
    "id" bigint generated by default as identity not null,
    "faculty_id" bigint not null,
    "name" text not null
      );


alter table "public"."appartment" enable row level security;


  create table "public"."chat" (
    "id" uuid not null,
    "sender_id" uuid,
    "receiver_id" uuid not null,
    "content" text,
    "create_at" timestamp with time zone default now()
      );


alter table "public"."chat" enable row level security;


  create table "public"."faculty" (
    "id" bigint generated by default as identity not null,
    "name" text not null
      );


alter table "public"."faculty" enable row level security;


  create table "public"."like" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "post_id" bigint not null
      );


alter table "public"."like" enable row level security;


  create table "public"."post" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "content" text not null,
    "image_url" text,
    "created_at" timestamp without time zone not null,
    "number_of_likes" bigint not null default '0'::bigint
      );


alter table "public"."post" enable row level security;


  create table "public"."reviews" (
    "id" uuid not null default gen_random_uuid(),
    "course_id" bigint not null,
    "review_text" text not null,
    "rating" smallint not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."reviews" enable row level security;


  create table "public"."textbook" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "author" text,
    "publisher" text,
    "isbn" text,
    "pub_year" text
      );


alter table "public"."textbook" enable row level security;


  create table "public"."txt_course" (
    "id" bigint generated always as identity not null,
    "txt_post_id" bigint,
    "textbook_isbn" text
      );


alter table "public"."txt_course" enable row level security;


  create table "public"."txt_matching" (
    "id" bigint generated by default as identity not null,
    "txt_post_id" bigint not null,
    "seller_id" uuid not null,
    "buyer_id" uuid not null,
    "status" text not null
      );


alter table "public"."txt_matching" enable row level security;


  create table "public"."txt_post" (
    "id" bigint generated by default as identity not null,
    "give_type" text not null,
    "user_id" uuid not null,
    "textbook_id" bigint not null,
    "condition_id" bigint,
    "price" bigint,
    "description" text,
    "status" text not null,
    "created_at" timestamp with time zone not null
      );


alter table "public"."txt_post" enable row level security;


  create table "public"."txtbook_condition" (
    "id" bigint generated by default as identity not null,
    "name" text not null
      );


alter table "public"."txtbook_condition" enable row level security;


  create table "public"."user" (
    "id" uuid not null,
    "username" text not null,
    "grade" bigint,
    "department_id" bigint,
    "icon_src" text
      );


alter table "public"."user" enable row level security;


  create table "public"."授業" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "professor" text,
    "day" text,
    "department" text,
    "lct_cd" text,
    "subject_no" text,
    "credits" double precision,
    "required" text,
    "appartment_id" bigint,
    "faculty_id" bigint
      );


alter table "public"."授業" enable row level security;

CREATE UNIQUE INDEX chat_pkey ON public.chat USING btree (id);

CREATE INDEX idx_reviews_course_id ON public.reviews USING btree (course_id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);

CREATE UNIQUE INDEX textbook_isbn_key ON public.textbook USING btree (isbn);

CREATE UNIQUE INDEX txt_course_pkey ON public.txt_course USING btree (id);

CREATE UNIQUE INDEX "いいね_pkey" ON public."like" USING btree (id);

CREATE UNIQUE INDEX "ポスト_pkey" ON public.post USING btree (id);

CREATE UNIQUE INDEX "ユーザー_pkey1" ON public."user" USING btree (id);

CREATE UNIQUE INDEX "学科_pkey" ON public.appartment USING btree (id);

CREATE UNIQUE INDEX "学部_pkey" ON public.faculty USING btree (id);

CREATE UNIQUE INDEX "授業_pkey" ON public."授業" USING btree (id);

CREATE UNIQUE INDEX "教科書_pkey" ON public.textbook USING btree (id);

CREATE UNIQUE INDEX "教科書コンディション_pkey" ON public.txtbook_condition USING btree (id);

CREATE UNIQUE INDEX "教科書ポスト_pkey1" ON public.txt_post USING btree (id);

CREATE UNIQUE INDEX "教科書マッチング_pkey" ON public.txt_matching USING btree (id);

alter table "public"."appartment" add constraint "学科_pkey" PRIMARY KEY using index "学科_pkey";

alter table "public"."chat" add constraint "chat_pkey" PRIMARY KEY using index "chat_pkey";

alter table "public"."faculty" add constraint "学部_pkey" PRIMARY KEY using index "学部_pkey";

alter table "public"."like" add constraint "いいね_pkey" PRIMARY KEY using index "いいね_pkey";

alter table "public"."post" add constraint "ポスト_pkey" PRIMARY KEY using index "ポスト_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."textbook" add constraint "教科書_pkey" PRIMARY KEY using index "教科書_pkey";

alter table "public"."txt_course" add constraint "txt_course_pkey" PRIMARY KEY using index "txt_course_pkey";

alter table "public"."txt_matching" add constraint "教科書マッチング_pkey" PRIMARY KEY using index "教科書マッチング_pkey";

alter table "public"."txt_post" add constraint "教科書ポスト_pkey1" PRIMARY KEY using index "教科書ポスト_pkey1";

alter table "public"."txtbook_condition" add constraint "教科書コンディション_pkey" PRIMARY KEY using index "教科書コンディション_pkey";

alter table "public"."user" add constraint "ユーザー_pkey1" PRIMARY KEY using index "ユーザー_pkey1";

alter table "public"."授業" add constraint "授業_pkey" PRIMARY KEY using index "授業_pkey";

alter table "public"."appartment" add constraint "学科_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES public.faculty(id) not valid;

alter table "public"."appartment" validate constraint "学科_faculty_id_fkey";

alter table "public"."chat" add constraint "chat_id_fkey" FOREIGN KEY (id) REFERENCES public."user"(id) not valid;

alter table "public"."chat" validate constraint "chat_id_fkey";

alter table "public"."chat" add constraint "chat_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public."user"(id) not valid;

alter table "public"."chat" validate constraint "chat_receiver_id_fkey";

alter table "public"."chat" add constraint "chat_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public."user"(id) not valid;

alter table "public"."chat" validate constraint "chat_sender_id_fkey";

alter table "public"."like" add constraint "いいね_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.post(id) not valid;

alter table "public"."like" validate constraint "いいね_post_id_fkey";

alter table "public"."like" add constraint "いいね_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(id) not valid;

alter table "public"."like" validate constraint "いいね_user_id_fkey";

alter table "public"."post" add constraint "ポスト_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(id) not valid;

alter table "public"."post" validate constraint "ポスト_user_id_fkey";

alter table "public"."reviews" add constraint "reviews_course_id_fkey" FOREIGN KEY (course_id) REFERENCES public."授業"(id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_course_id_fkey";

alter table "public"."reviews" add constraint "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5))) not valid;

alter table "public"."reviews" validate constraint "reviews_rating_check";

alter table "public"."textbook" add constraint "textbook_isbn_key" UNIQUE using index "textbook_isbn_key";

alter table "public"."txt_course" add constraint "txt_course_textbook_isbn_fkey" FOREIGN KEY (textbook_isbn) REFERENCES public.textbook(isbn) not valid;

alter table "public"."txt_course" validate constraint "txt_course_textbook_isbn_fkey";

alter table "public"."txt_course" add constraint "txt_course_txt_post_id_fkey" FOREIGN KEY (txt_post_id) REFERENCES public."授業"(id) not valid;

alter table "public"."txt_course" validate constraint "txt_course_txt_post_id_fkey";

alter table "public"."txt_matching" add constraint "教科書マッチング_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES public."user"(id) not valid;

alter table "public"."txt_matching" validate constraint "教科書マッチング_buyer_id_fkey";

alter table "public"."txt_matching" add constraint "教科書マッチング_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES public."user"(id) not valid;

alter table "public"."txt_matching" validate constraint "教科書マッチング_seller_id_fkey";

alter table "public"."txt_matching" add constraint "教科書マッチング_txt_post_id_fkey" FOREIGN KEY (txt_post_id) REFERENCES public.txt_post(id) not valid;

alter table "public"."txt_matching" validate constraint "教科書マッチング_txt_post_id_fkey";

alter table "public"."txt_post" add constraint "教科書ポスト_condition_id_fkey" FOREIGN KEY (condition_id) REFERENCES public.txtbook_condition(id) not valid;

alter table "public"."txt_post" validate constraint "教科書ポスト_condition_id_fkey";

alter table "public"."txt_post" add constraint "教科書ポスト_textbook_id_fkey" FOREIGN KEY (textbook_id) REFERENCES public.textbook(id) not valid;

alter table "public"."txt_post" validate constraint "教科書ポスト_textbook_id_fkey";

alter table "public"."txt_post" add constraint "教科書ポスト_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(id) not valid;

alter table "public"."txt_post" validate constraint "教科書ポスト_user_id_fkey";

alter table "public"."user" add constraint "ユーザー_department_id_fkey1" FOREIGN KEY (department_id) REFERENCES public.appartment(id) not valid;

alter table "public"."user" validate constraint "ユーザー_department_id_fkey1";

alter table "public"."授業" add constraint "授業_appartment_id_fkey" FOREIGN KEY (appartment_id) REFERENCES public.appartment(id) not valid;

alter table "public"."授業" validate constraint "授業_appartment_id_fkey";

alter table "public"."授業" add constraint "授業_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES public.faculty(id) not valid;

alter table "public"."授業" validate constraint "授業_faculty_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$declare
  allowed_domain text := 'cs.u-ryukyu.ac.jp'; -- 宣言は残っていますが、下のIF文を消せば制限はかかりません
begin
  if (new.email not like '%@cs.u-ryukyu.ac.jp') then
    raise exception '許可されていないメールドメインです';
  end if;

  insert into public.ユーザー (id, username, grade, department_id)
  values (
    new.id,
    new.raw_user_meta_data->>'username',
    (new.raw_user_meta_data->>'grade')::bigint,
    (new.raw_user_meta_data->>'department_id')::bigint
  );
  return new;
end;$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."appartment" to "anon";

grant insert on table "public"."appartment" to "anon";

grant references on table "public"."appartment" to "anon";

grant select on table "public"."appartment" to "anon";

grant trigger on table "public"."appartment" to "anon";

grant truncate on table "public"."appartment" to "anon";

grant update on table "public"."appartment" to "anon";

grant delete on table "public"."appartment" to "authenticated";

grant insert on table "public"."appartment" to "authenticated";

grant references on table "public"."appartment" to "authenticated";

grant select on table "public"."appartment" to "authenticated";

grant trigger on table "public"."appartment" to "authenticated";

grant truncate on table "public"."appartment" to "authenticated";

grant update on table "public"."appartment" to "authenticated";

grant delete on table "public"."appartment" to "service_role";

grant insert on table "public"."appartment" to "service_role";

grant references on table "public"."appartment" to "service_role";

grant select on table "public"."appartment" to "service_role";

grant trigger on table "public"."appartment" to "service_role";

grant truncate on table "public"."appartment" to "service_role";

grant update on table "public"."appartment" to "service_role";

grant delete on table "public"."chat" to "anon";

grant insert on table "public"."chat" to "anon";

grant references on table "public"."chat" to "anon";

grant select on table "public"."chat" to "anon";

grant trigger on table "public"."chat" to "anon";

grant truncate on table "public"."chat" to "anon";

grant update on table "public"."chat" to "anon";

grant delete on table "public"."chat" to "authenticated";

grant insert on table "public"."chat" to "authenticated";

grant references on table "public"."chat" to "authenticated";

grant select on table "public"."chat" to "authenticated";

grant trigger on table "public"."chat" to "authenticated";

grant truncate on table "public"."chat" to "authenticated";

grant update on table "public"."chat" to "authenticated";

grant delete on table "public"."chat" to "service_role";

grant insert on table "public"."chat" to "service_role";

grant references on table "public"."chat" to "service_role";

grant select on table "public"."chat" to "service_role";

grant trigger on table "public"."chat" to "service_role";

grant truncate on table "public"."chat" to "service_role";

grant update on table "public"."chat" to "service_role";

grant delete on table "public"."faculty" to "anon";

grant insert on table "public"."faculty" to "anon";

grant references on table "public"."faculty" to "anon";

grant select on table "public"."faculty" to "anon";

grant trigger on table "public"."faculty" to "anon";

grant truncate on table "public"."faculty" to "anon";

grant update on table "public"."faculty" to "anon";

grant delete on table "public"."faculty" to "authenticated";

grant insert on table "public"."faculty" to "authenticated";

grant references on table "public"."faculty" to "authenticated";

grant select on table "public"."faculty" to "authenticated";

grant trigger on table "public"."faculty" to "authenticated";

grant truncate on table "public"."faculty" to "authenticated";

grant update on table "public"."faculty" to "authenticated";

grant delete on table "public"."faculty" to "service_role";

grant insert on table "public"."faculty" to "service_role";

grant references on table "public"."faculty" to "service_role";

grant select on table "public"."faculty" to "service_role";

grant trigger on table "public"."faculty" to "service_role";

grant truncate on table "public"."faculty" to "service_role";

grant update on table "public"."faculty" to "service_role";

grant delete on table "public"."like" to "anon";

grant insert on table "public"."like" to "anon";

grant references on table "public"."like" to "anon";

grant select on table "public"."like" to "anon";

grant trigger on table "public"."like" to "anon";

grant truncate on table "public"."like" to "anon";

grant update on table "public"."like" to "anon";

grant delete on table "public"."like" to "authenticated";

grant insert on table "public"."like" to "authenticated";

grant references on table "public"."like" to "authenticated";

grant select on table "public"."like" to "authenticated";

grant trigger on table "public"."like" to "authenticated";

grant truncate on table "public"."like" to "authenticated";

grant update on table "public"."like" to "authenticated";

grant delete on table "public"."like" to "service_role";

grant insert on table "public"."like" to "service_role";

grant references on table "public"."like" to "service_role";

grant select on table "public"."like" to "service_role";

grant trigger on table "public"."like" to "service_role";

grant truncate on table "public"."like" to "service_role";

grant update on table "public"."like" to "service_role";

grant delete on table "public"."post" to "anon";

grant insert on table "public"."post" to "anon";

grant references on table "public"."post" to "anon";

grant select on table "public"."post" to "anon";

grant trigger on table "public"."post" to "anon";

grant truncate on table "public"."post" to "anon";

grant update on table "public"."post" to "anon";

grant delete on table "public"."post" to "authenticated";

grant insert on table "public"."post" to "authenticated";

grant references on table "public"."post" to "authenticated";

grant select on table "public"."post" to "authenticated";

grant trigger on table "public"."post" to "authenticated";

grant truncate on table "public"."post" to "authenticated";

grant update on table "public"."post" to "authenticated";

grant delete on table "public"."post" to "service_role";

grant insert on table "public"."post" to "service_role";

grant references on table "public"."post" to "service_role";

grant select on table "public"."post" to "service_role";

grant trigger on table "public"."post" to "service_role";

grant truncate on table "public"."post" to "service_role";

grant update on table "public"."post" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

grant delete on table "public"."textbook" to "anon";

grant insert on table "public"."textbook" to "anon";

grant references on table "public"."textbook" to "anon";

grant select on table "public"."textbook" to "anon";

grant trigger on table "public"."textbook" to "anon";

grant truncate on table "public"."textbook" to "anon";

grant update on table "public"."textbook" to "anon";

grant delete on table "public"."textbook" to "authenticated";

grant insert on table "public"."textbook" to "authenticated";

grant references on table "public"."textbook" to "authenticated";

grant select on table "public"."textbook" to "authenticated";

grant trigger on table "public"."textbook" to "authenticated";

grant truncate on table "public"."textbook" to "authenticated";

grant update on table "public"."textbook" to "authenticated";

grant delete on table "public"."textbook" to "service_role";

grant insert on table "public"."textbook" to "service_role";

grant references on table "public"."textbook" to "service_role";

grant select on table "public"."textbook" to "service_role";

grant trigger on table "public"."textbook" to "service_role";

grant truncate on table "public"."textbook" to "service_role";

grant update on table "public"."textbook" to "service_role";

grant delete on table "public"."txt_course" to "anon";

grant insert on table "public"."txt_course" to "anon";

grant references on table "public"."txt_course" to "anon";

grant select on table "public"."txt_course" to "anon";

grant trigger on table "public"."txt_course" to "anon";

grant truncate on table "public"."txt_course" to "anon";

grant update on table "public"."txt_course" to "anon";

grant delete on table "public"."txt_course" to "authenticated";

grant insert on table "public"."txt_course" to "authenticated";

grant references on table "public"."txt_course" to "authenticated";

grant select on table "public"."txt_course" to "authenticated";

grant trigger on table "public"."txt_course" to "authenticated";

grant truncate on table "public"."txt_course" to "authenticated";

grant update on table "public"."txt_course" to "authenticated";

grant delete on table "public"."txt_course" to "service_role";

grant insert on table "public"."txt_course" to "service_role";

grant references on table "public"."txt_course" to "service_role";

grant select on table "public"."txt_course" to "service_role";

grant trigger on table "public"."txt_course" to "service_role";

grant truncate on table "public"."txt_course" to "service_role";

grant update on table "public"."txt_course" to "service_role";

grant delete on table "public"."txt_matching" to "anon";

grant insert on table "public"."txt_matching" to "anon";

grant references on table "public"."txt_matching" to "anon";

grant select on table "public"."txt_matching" to "anon";

grant trigger on table "public"."txt_matching" to "anon";

grant truncate on table "public"."txt_matching" to "anon";

grant update on table "public"."txt_matching" to "anon";

grant delete on table "public"."txt_matching" to "authenticated";

grant insert on table "public"."txt_matching" to "authenticated";

grant references on table "public"."txt_matching" to "authenticated";

grant select on table "public"."txt_matching" to "authenticated";

grant trigger on table "public"."txt_matching" to "authenticated";

grant truncate on table "public"."txt_matching" to "authenticated";

grant update on table "public"."txt_matching" to "authenticated";

grant delete on table "public"."txt_matching" to "service_role";

grant insert on table "public"."txt_matching" to "service_role";

grant references on table "public"."txt_matching" to "service_role";

grant select on table "public"."txt_matching" to "service_role";

grant trigger on table "public"."txt_matching" to "service_role";

grant truncate on table "public"."txt_matching" to "service_role";

grant update on table "public"."txt_matching" to "service_role";

grant delete on table "public"."txt_post" to "anon";

grant insert on table "public"."txt_post" to "anon";

grant references on table "public"."txt_post" to "anon";

grant select on table "public"."txt_post" to "anon";

grant trigger on table "public"."txt_post" to "anon";

grant truncate on table "public"."txt_post" to "anon";

grant update on table "public"."txt_post" to "anon";

grant delete on table "public"."txt_post" to "authenticated";

grant insert on table "public"."txt_post" to "authenticated";

grant references on table "public"."txt_post" to "authenticated";

grant select on table "public"."txt_post" to "authenticated";

grant trigger on table "public"."txt_post" to "authenticated";

grant truncate on table "public"."txt_post" to "authenticated";

grant update on table "public"."txt_post" to "authenticated";

grant delete on table "public"."txt_post" to "service_role";

grant insert on table "public"."txt_post" to "service_role";

grant references on table "public"."txt_post" to "service_role";

grant select on table "public"."txt_post" to "service_role";

grant trigger on table "public"."txt_post" to "service_role";

grant truncate on table "public"."txt_post" to "service_role";

grant update on table "public"."txt_post" to "service_role";

grant delete on table "public"."txtbook_condition" to "anon";

grant insert on table "public"."txtbook_condition" to "anon";

grant references on table "public"."txtbook_condition" to "anon";

grant select on table "public"."txtbook_condition" to "anon";

grant trigger on table "public"."txtbook_condition" to "anon";

grant truncate on table "public"."txtbook_condition" to "anon";

grant update on table "public"."txtbook_condition" to "anon";

grant delete on table "public"."txtbook_condition" to "authenticated";

grant insert on table "public"."txtbook_condition" to "authenticated";

grant references on table "public"."txtbook_condition" to "authenticated";

grant select on table "public"."txtbook_condition" to "authenticated";

grant trigger on table "public"."txtbook_condition" to "authenticated";

grant truncate on table "public"."txtbook_condition" to "authenticated";

grant update on table "public"."txtbook_condition" to "authenticated";

grant delete on table "public"."txtbook_condition" to "service_role";

grant insert on table "public"."txtbook_condition" to "service_role";

grant references on table "public"."txtbook_condition" to "service_role";

grant select on table "public"."txtbook_condition" to "service_role";

grant trigger on table "public"."txtbook_condition" to "service_role";

grant truncate on table "public"."txtbook_condition" to "service_role";

grant update on table "public"."txtbook_condition" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";

grant delete on table "public"."授業" to "anon";

grant insert on table "public"."授業" to "anon";

grant references on table "public"."授業" to "anon";

grant select on table "public"."授業" to "anon";

grant trigger on table "public"."授業" to "anon";

grant truncate on table "public"."授業" to "anon";

grant update on table "public"."授業" to "anon";

grant delete on table "public"."授業" to "authenticated";

grant insert on table "public"."授業" to "authenticated";

grant references on table "public"."授業" to "authenticated";

grant select on table "public"."授業" to "authenticated";

grant trigger on table "public"."授業" to "authenticated";

grant truncate on table "public"."授業" to "authenticated";

grant update on table "public"."授業" to "authenticated";

grant delete on table "public"."授業" to "service_role";

grant insert on table "public"."授業" to "service_role";

grant references on table "public"."授業" to "service_role";

grant select on table "public"."授業" to "service_role";

grant trigger on table "public"."授業" to "service_role";

grant truncate on table "public"."授業" to "service_role";

grant update on table "public"."授業" to "service_role";


  create policy "学科は誰でも参照可能"
  on "public"."appartment"
  as permissive
  for select
  to public
using (true);



  create policy "学部は誰でも参照可能"
  on "public"."faculty"
  as permissive
  for select
  to public
using (true);



  create policy "全操作可能"
  on "public"."like"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "全操作可能"
  on "public"."post"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "全操作可能"
  on "public"."textbook"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "全操作可能"
  on "public"."txt_matching"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "全操作可能"
  on "public"."txt_post"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "全操作可能"
  on "public"."txtbook_condition"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "全操作可能"
  on "public"."user"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "全操作可能"
  on "public"."授業"
  as permissive
  for all
  to public
using (true)
with check (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


